/* Group 25 :
Members:
    Ishaan Pavan Gupta 2022A7PS1180P
    Aayush Gupta       2022A7PS0088P
    Saksham Jain       2022A7PS0132P
    Mudit Gupta        2022A7PS0178P
    Aditi Bansal       2022A7PS0053P
    Kshitiz Gupta      2022A7PS0057P
 */

#include<stdio.h>
#include "lexer.h"
#include "interface.h"
#include <time.h>

int main(int argc, char* argv[])
{
    int opt;
    //$./stage1exe  testcase.txt  parsetreeOutFile.txt
    if (argc == 1)
    {
        printf("No input file provided\n");
        return 0;
    }
    else if (argc == 2)
    {
        printf("Output file not provided\n");
        return 0;   
    }
    else if (argc > 3)
    {
        printf("Too many arguments\n");
        return 0;
    }
    else
    {
        printf("Input file: %s\n", argv[1]);
        printf("Output file: %s\n", argv[2]);
    }

    printf("Welcome to Compiler Project - Group no. 25\n");
    printf("--------------------------------\n");
    printf("Enter 0 for exit\n");
    printf("Enter 1 for removal of comments\n");
    printf("Enter 2 for printing tokens generated by the lexer\n");
    printf("Enter 3 For syntactic correctness of the input source code and printing the parse tree\n");
    printf("Enter 4 for total time taken by the program\n");
    
    clock_t start_time, end_time;
    double total_CPU_time, total_CPU_time_in_seconds;

    while (1)
    {
        printf("Enter your choice: ");
        scanf("%d", &opt);
        if (opt == 0)
        {
            break;
        }
        else if (opt == 1)
        {
            // invoke your lexer here
            printf("Printing comment free code \n");
            printf("---------------------------\n");
            int fp = open(argv[1],O_RDONLY);
            // printf("1");
            TwinBuffer* B = initializeLexer(fp);
            if (B == NULL) {
                printf("Memory allocation failed while initializing lexer\n");
                close(fp);
                continue; // Avoid segmentation fault
            }
            // printf("2");
            removeComments(argv[1],B,argv[2]);
            // printf("3");
            printf("\nFinished printing comment free code \n");
        
        }
        else if (opt == 2)
        {
            // invoke your lexer here
            printf("Printing tokens: \n");
            printf("------------------\n");
            int fp = open(argv[1],O_RDONLY);
           /*  FILE * out;
            out = fopen(argv[2],"w"); */
            Token * t;
            TwinBuffer* B = initializeLexer(fp);
            if (B == NULL) {
                printf("Memory allocation failed while initializing lexer\n");
                close(fp);
                continue; // Avoid segmentation fault
            }
            if (fp == -1) {
                printf("Error opening file\n");
                free(B);
                continue;
            }
            int cnt = 0;
            while((t = getToken(B)) != NULL) {
                // Write token details to the output file
                // fprintf(out, "Line no. %d\t Lexeme %s\t Token %s\n", t->LINE_NO, t->LEXEME, getTerminal(t->TOKEN_NAME));
                
                printf("Line no. %d\t Lexeme %s\t Token %s\n", t->LINE_NO, t->LEXEME, getTerminal(t->TOKEN_NAME));
                cnt++;
                free(t);
            }
            printf("Line final %d", cnt);
            // fclose(out);
            close(fp);

            printf("\nFinished printing of token list \n");

        }
        else if (opt == 3 || opt == 4)
        {
            // invoke your lexer and parser here
            start_time = clock();

            /* Grammar* g = extractGrammar();
            FirstAndFollow* fafl = computeFirstAndFollowSets(g);
            ParsingTable* pTable = initialiseParsingTable();
            createParseTable(fafl,pTable);
            // Lexer and parser are both invoked inside parseInputSourceCode
            ParseTree* pt = parseInputSourceCode(argv[1],pTable,fafl); */
            //if (opt ==3) printParseTree(pt,NULL);

            end_time = clock();

            printf("\nFinished parsing of input source code \n");

            if(opt == 4){

                total_CPU_time = (double) (end_time - start_time);
                total_CPU_time_in_seconds = total_CPU_time / CLOCKS_PER_SEC;
                printf("Total time taken by CPU: %f\n", total_CPU_time);
                printf("Total time taken by CPU in seconds: %f\n", total_CPU_time_in_seconds);

            }
        }
        else
        {
            printf("Invalid choice, Kindly chose an option from 0 to 4\n");
        }
    }

    return 0;
}
