/* Group no. 25
* Members:
*/

#include<stdio.h>
#include "lexer.h"
#include "interface.h"
#include <time.h>

int main(int argc, char* argv[])
{
    int opt;
    //$./stage1exe  testcase.txt  parsetreeOutFile.txt
    if (argc == 1)
    {
        printf("No input file provided\n");
        return 0;
    }
    else if (argc == 2)
    {
        printf("Output file not provided\n");
        return 0;   
    }
    else if (argc > 3)
    {
        printf("Too many arguments\n");
        return 0;
    }
    else
    {
        printf("Input file: %s\n", argv[1]);
        printf("Output file: %s\n", argv[2]);
    }

    printf("Welcome to Compiler Project - Group no. 25\n");
    printf("--------------------------------\n");
    printf("Enter 0 for exit\n");
    printf("Enter 1 for removal of comments\n");
    printf("Enter 2 for printing tokens generated by the lexer\n");
    printf("Enter 3 For syntactic correctness of the input source code and printing the parse tree\n");
    printf("Enter 4 for total time taken by the program\n");
    
    clock_t start_time, end_time;
    double total_CPU_time, total_CPU_time_in_seconds;

    while (1)
    {
        printf("Enter your choice: ");
        scanf("%d", &opt);
        if (opt == 0)
        {
            break;
        }
        else if (opt == 1)
        {
            // invoke your lexer here
            printf("Printing comment free code \n");
            printf("---------------------------\n");
            TwinBuffer* B = (TwinBuffer*)malloc(sizeof(TwinBuffer));
            initializeTwinBuffer(B);
            removeComments(argv[1],B);
            printf("\nFinished printing comment free code \n");
        
        }
        else if (opt == 2)
        {
            // invoke your lexer here
            printf("Printing tokens: \n");
            printf("------------------\n");
            int fp = open(argv[1],"r");
            initializeLexer(fp);
            Token * t;
            TwinBuffer* B = (TwinBuffer*)malloc(sizeof(TwinBuffer));
            initializeTwinBuffer(B);
            while((t = getToken(B)) != NULL) {
                printf("%s        %s        %d \n", getTerminal(t->TOKEN_NAME),t->LEXEME,t->LINE_NO);
            }
            close(fp);

            printf("\nFinished printing of token list \n");

        }
        else if (opt == 3 || opt == 4)
        {
            // invoke your lexer and parser here
            start_time = clock();

            /* Grammar* g = extractGrammar();
            FirstAndFollow* fafl = computeFirstAndFollowSets(g);
            ParsingTable* pTable = initialiseParsingTable();
            createParseTable(fafl,pTable);
            // Lexer and parser are both invoked inside parseInputSourceCode
            ParseTree* pt = parseInputSourceCode(argv[1],pTable,fafl); */
            //if (opt ==3) printParseTree(pt,NULL);

            end_time = clock();

            printf("\nFinished parsing of input source code \n");

            if(opt == 4){

                total_CPU_time = (double) (end_time - start_time);
                total_CPU_time_in_seconds = total_CPU_time / CLOCKS_PER_SEC;
                printf("Total time taken by CPU: %f\n", total_CPU_time);
                printf("Total time taken by CPU in seconds: %f\n", total_CPU_time_in_seconds);

            }
        }
        else
        {
            printf("Invalid choice, Kindly chose an option from 0 to 4\n");
        }
    }

    return 0;
}
